options:
  plugin:
    default: ovs
    type: string
    description: |
      Network configuration plugin to use for quantum.
      Supported values include:
      .
        ovs - OpenVSwitch
        nvp|nsx - Nicira NVP/VMware NSX
  ext-port:
    type: string
    description: |
      External port to use for routing of instance
      traffic to the external public network.
  openstack-origin:
    type: string
    default: distro
    description: |
      Optional configuration to support use of additional sources such as:
      .
        - ppa:myteam/ppa
        - cloud:precise-folsom/proposed
        - cloud:precise-folsom
        - deb http://my.archive.com/ubuntu main|KEYID
      .
      Note that quantum/neutron is only supported >= Folsom.
  run-internal-router:
    type: string
    default: all
    description: |
      Optional configuration to support how the L3 agent option
      handle_internal_only_routers is configured.
      all    => Set to be true everywhere
      none   => Set to be false everywhere
      leader => Set to be true on one node (the leader) and false everywhere
                else.
      Use leader and none when configuring multiple floating pools
  external-network-id:
    type: string
    description: |
      Optional configuration to set the external-network-id. Only needed when
      configuring multiple external networks and should be used in conjunction
      with run-internal-router.
  rabbit-user:
    type: string
    description: RabbitMQ user
    default: neutron
  rabbit-vhost:
    type: string
    description: RabbitMQ Virtual Host
    default: openstack
  debug:
    default: False
    type: boolean
    description: Enable debug logging
  verbose:
    default: False
    type: boolean
    description: Enable verbose logging
  use-syslog:
    type: boolean
    default: False
    description: |
      If set to True, supporting services will log to syslog.
  instance-mtu:
    type: int
    description: |
      Configure DHCP services to provide MTU configuration to instances
      within the cloud.  This is useful in deployments where its not
      possible to increase MTU on switches and physical servers to
      accomodate the packet overhead of using GRE tunnels.
  database-user:
    default: nova
    type: string
    description: Username for database access
  database:
    default: nova
    type: string
    description: Database name
